### ISSUE TITLE
why hard value is used

### ISSUE THREAD

**Issue by Rishi9868** [shivshankar0965/indiwebmall#43]
https://github.com/shivshankar0965/general-protest-6773/blob/2e474e87631afbae91e6fe2a1f8107502c88596f/src/Components/Vouchers/VoucherOne.jsx#L105

**Comment by deepakkumarfathkar** [comment]
Because there are many data and I want to show a small amount of data to the users in a single slide so I used there hard value

**Comment by deep1296** [comment]
Done
